#for managing all the live constants here so that  other modules can import values from here

import os
from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")


#directory where chromaDB stores its data
CHROMA_PATH = "./chroma_db"

#name of chroma collection
COLLECTION_NAME = "research_papers"

# embedding model
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

#chunking configuration

#no of chars in each chunk
CHUNK_SIZE = 500

#no of overlapping chars bet chunks
CHUNK_OVERLAP = 100

#retrieval cinfiguration

#default no of chunks retrieved for every query
TOP_K = 5

#groq configuration

#llm used for ans generation
GROQ_MODEL = "llama-3.3-70b-versatile"

#generation settings

TEMPERATURE = 0.2

#limits the size of text generated by llm
MAX_TOKENS= 1024  


DATA_DIR = "./data"

PAPERS_DIR = os.path.join(DATA_DIR, "papers")

os.makedirs(PAPERS_DIR, exist_ok=True)

os.makedirs(CHROMA_PATH, exist_ok=True)

# File uploads — temp storage before ingestion
UPLOAD_DIR = "./uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)


JWT_SECRET_KEY   = os.getenv("JWT_SECRET_KEY", "change-me-in-production")
JWT_ALGORITHM    = "HS256"
JWT_EXPIRE_HOURS = 24